Feature/contacts
MaksymFrankov/IceCream pull request #23
Opened 2022-06-10 16:23 UTC by yevhen-arkhipov

сделал оформление и адаптивку, в следующем коммите будут кнопки
проверить и зслить можно только  4fc760c

2022-06-10 18:24 UTC, Alla-Goptsii commented on src/partials/contacts.html
> -        <ul class="contacts__list list">
считаю, что нужно карточки сделать одной ul

2022-06-10 18:26 UTC, Alla-Goptsii commented on src/partials/contacts.html
> +                <p class="contacts__text contacts__text--orange">Cafe</p>
классьі назвать без обозначения цвета contacts__text--orange напр. contacts__text--first

2022-06-10 18:33 UTC, Alla-Goptsii commented on src/partials/contacts.html
> +            <button class="button">Franchise</button>
<svg width="4" height="8" class="suffix">
    <use href="./images/icons.svg#icon-button-svg-light"></use>
  </svg>

2022-06-10 18:35 UTC, Alla-Goptsii commented on src/partials/contacts.html
> +            <button class="button">Our Locations</button>
<svg width="5" height="8" class="suffix">
    <use href="./images/icons.svg#icon-button-svg-dark"></use>
  </svg>

2022-06-10 18:38 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        padding: 40px 32px;
лучше указать padding-top:40px;  padding-left: 32px; т.к. справа паддинга нет

2022-06-10 18:45 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        &:not(:first-child) {
тьі когда изменишь структуру по карточкам ul>li ... тогда изменятся и классьі немного. желательно оставить везде по проекту одно напрвление right-botom u last-child или left-top u first-child. может получится так раздать марджиньі.

2022-06-10 18:56 UTC, yevhen-arkhipov commented on src/partials/contacts.html
> -        <ul class="contacts__list list">
уже фиксю)

2022-06-10 18:57 UTC, yevhen-arkhipov commented on src/partials/contacts.html
> +                <p class="contacts__text contacts__text--orange">Cafe</p>
тут как раз наоборот вроде, модификатор должен говорить о том, что он делает

2022-06-10 18:59 UTC, yevhen-arkhipov commented on src/sass/layouts/_contacts.scss
> +        padding: 40px 32px;
есть, там border-bottom будет тогда тянуться до конца вправо)

2022-06-10 19:01 UTC, yevhen-arkhipov commented on src/sass/layouts/_contacts.scss
> +        &:not(:first-child) {
там в местах не выходит по другому, где-то нужно что-то дать первому, а где-то другому, попробую и тогда глянем еще раз

2022-06-10 20:24 UTC, Alla-Goptsii commented on src/partials/contacts.html
> +                <p class="contacts__text contacts__text--orange">Cafe</p>
да, перечитала конспект, все верно, сори))

2022-06-10 21:45 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +            padding: 0 18px;
опечатка - 0 16рх;

2022-06-10 21:46 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        @include desktop {
т.к. в таблетке pudding: 16рх то наследуется и строки 35 и 36 не надо

2022-06-10 21:48 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        @include mobile-horizontal {
здесь , наверное, вместо mobile-horizontal - tablet?

2022-06-10 21:50 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        @include mobile-horizontal {
и строки 182 и 197 тоже, или там задумка такая?)))

2022-06-10 22:07 UTC, yevhen-arkhipov commented on src/sass/layouts/_contacts.scss
> +        @include desktop {
та как раз в этом и проблема, изначально я так и сделал, но на макете в таблетке 18px, вот сижу и ломаю голову

2022-06-10 22:08 UTC, yevhen-arkhipov commented on src/sass/layouts/_contacts.scss
> +        @include mobile-horizontal {
да, карточка больше становиться, лучше выглядит)

2022-06-11 04:28 UTC, MaksymFrankov requested changes
Удали плиз css папку, и просьба если используешь scss live - не забывай удалять потом то, что он сгенерил

2022-06-11 08:15 UTC, Alla-Goptsii commented on src/sass/layouts/_contacts.scss
> +        @include desktop {
у меня 16, может что-то сьехало на фигме?

2022-06-11 08:25 UTC, MaksymFrankov approved these changes

2022-06-11 08:25 UTC, merged